name: Test

on:
  issues:
    types:
      - opened
      - edited

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 main.py
        env:
          ISSUE_CONTEXT: "${{ toJSON(github.event.issue) }}"
