name: Test

on:
  issues:
    types:
      - opened
      - edited

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ISSUE_CONTEXT=${{ fromJson(github.event) }} python3 main.py
