name: Test

on:
  issues:
    types:
      - opened
      - edited

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: python3 main.py
        env:
          ISSUE_CONTEXT: ${{ github.event.issue }}
